steps:
  integrationArtifactDeploy:
    ServiceKeyCred: bdcpiqa.it
    integrationFlowId: 202564-flow4
  integrationArtifactGetMplStatus:
    ServiceKeyCred: bdcpiqa.it
    integrationFlowId: 202564-flow4
  integrationArtifactUpload:
    ServiceKeyCred: bdcpiqa.it
    integrationFlowId: 202564-flow4
    integrationFlowName: 202564-flow4
    packageId: CICD
    filePath: 202564-flow4.zip
    verbose: true
