steps:
  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: techedServiceKeyCred
    integrationFlowId: 202564-flow4
  integrationArtifactGetMplStatus:
    cpiApiServiceKeyCredentialsId: techedServiceKeyCred
    integrationFlowId: 202564-flow4
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: techedServiceKeyCred
    integrationFlowId: 202564-flow4
    integrationFlowName: 202564-flow4
    packageId: CICD
    filePath: 202564-flow4.zip